-- 1. PAÍS
CREATE TABLE PAIS (
    idPais NUMBER(3) PRIMARY KEY NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    continente VARCHAR2(30) NOT NULL,
    moneda VARCHAR2(30) NOT NULL,
    nacionalidad VARCHAR2(50) NOT NULL
);

-- 2. CIUDAD
CREATE TABLE CIUDAD (
    idCiudad NUMBER(4) PRIMARY KEY NOT NULL,
    idPais NUMBER(3) NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_CIUDAD_PAIS FOREIGN KEY (idPais) REFERENCES PAIS(idPais)
);

-- 3. INSTITUCION
CREATE TABLE INSTITUCION (
    idInstitucion NUMBER(4) PRIMARY KEY NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    CONSTRAINT CHECK_TIPO_INST CHECK (tipo IN ('biblioteca', 'universidad', 'colegio', 'otro'))
);

-- 4. CLUB DE LECTURA
CREATE TABLE CLUB_LECTURA (
    idClub NUMBER(4) PRIMARY KEY NOT NULL,
    idCiudad NUMBER(4) NOT NULL,
    idInstitucion NUMBER(4), -- Puede ser NULL si el club es independiente
    nombre VARCHAR2(100) NOT NULL,
    calle_av VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    codigo_postal VARCHAR2(10) NOT NULL,
    cuota_membresia VARCHAR2(2) NOT NULL,
    CONSTRAINT FK_CLUB_CIUDAD FOREIGN KEY (idCiudad) REFERENCES CIUDAD(idCiudad),
    CONSTRAINT FK_CLUB_INSTITUCION FOREIGN KEY (idInstitucion) REFERENCES INSTITUCION(idInstitucion),
    CONSTRAINT CHECK_CUOTA CHECK (cuota_membresia IN ('si', 'no'))
);

-- 5. ASOCIADO (Relación de Clubes de Lectura entre sí)
CREATE TABLE CLUB_ASOCIADO (
    idClub1 NUMBER(4) NOT NULL,
    idClub2 NUMBER(4) NOT NULL,
    CONSTRAINT PK_CLUB_ASOCIADO PRIMARY KEY (idClub1, idClub2),
    CONSTRAINT FK_ASOC_CLUB1 FOREIGN KEY (idClub1) REFERENCES CLUB_LECTURA(idClub),
    CONSTRAINT FK_ASOC_CLUB2 FOREIGN KEY (idClub2) REFERENCES CLUB_LECTURA(idClub)
);

-- 6. IDIOMA
CREATE TABLE IDIOMA (
    idIdioma NUMBER(3) PRIMARY KEY NOT NULL,
    nombre VARCHAR2(30) NOT NULL
);

-- 7. CLUB_IDIOMA (Relación M:N entre Club e Idioma)
CREATE TABLE CLUB_IDIOMA (
    idClub NUMBER(4) NOT NULL,
    idIdioma NUMBER(3) NOT NULL,
    CONSTRAINT PK_CLUB_IDIOMA PRIMARY KEY (idClub, idIdioma),
    CONSTRAINT FK_CI_CLUB FOREIGN KEY (idClub) REFERENCES CLUB_LECTURA(idClub),
    CONSTRAINT FK_CI_IDIOMA FOREIGN KEY (idIdioma) REFERENCES IDIOMA(idIdioma)
);

-- 8. GRUPO LECTURA
CREATE TABLE GRUPO_LECTURA (
    idGrupo NUMBER(4) PRIMARY KEY NOT NULL,
    idClub NUMBER(4) NOT NULL,
    tipo VARCHAR2(10) NOT NULL,
    fecha_creacion DATE NOT NULL,
    dia_reunion VARCHAR2(15) NOT NULL,
    hora_i VARCHAR2(5) NOT NULL,
    CONSTRAINT FK_GRUPO_CLUB FOREIGN KEY (idClub) REFERENCES CLUB_LECTURA(idClub),
    CONSTRAINT CHECK_TIPO_GRUPO CHECK (tipo IN ('adulto', 'joven', 'niño'))
);

-- 9. CALENDARIO MES REUNION
CREATE TABLE CALENDARIO_MES_REUNION (
    fecha DATE NOT NULL,
    idGrupo NUMBER(4) NOT NULL,
    conclusiones VARCHAR2(500),
    ultima_discusion VARCHAR2(500),
    valoracion_final NUMBER(1),
    realizada VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_CALENDARIO PRIMARY KEY (fecha, idGrupo),
    CONSTRAINT FK_CALENDARIO_GRUPO FOREIGN KEY (idGrupo) REFERENCES GRUPO_LECTURA(idGrupo),
    CONSTRAINT CHECK_REALIZADA CHECK (realizada IN ('si', 'no')),
    CONSTRAINT CHECK_VALORACION CHECK (valoracion_final BETWEEN 1 AND 5)
);

-- 10. REPRESENTANTE
CREATE TABLE REPRESENTANTE (
    idRepresentante NUMBER(6) PRIMARY KEY NOT NULL,
    doc_identidad VARCHAR2(15) NOT NULL,
    primer_nombre VARCHAR2(30) NOT NULL,
    segundo_nombre VARCHAR2(30),
    primer_apellido VARCHAR2(30) NOT NULL,
    segundo_apellido VARCHAR2(30),
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    email VARCHAR2(50) NOT NULL
);

-- 11. MIEMBRO
CREATE TABLE MIEMBRO (
    idMiembro NUMBER(6) PRIMARY KEY NOT NULL,
    idRepresentante NUMBER(6), -- Puede ser NULL si es un adulto
    idPais_nacio NUMBER(3) NOT NULL,
    idGrupo NUMBER(4) NOT NULL,
    doc_identidad VARCHAR2(15) NOT NULL,
    primer_nombre VARCHAR2(30) NOT NULL,
    segundo_nombre VARCHAR2(30),
    primer_apellido VARCHAR2(30) NOT NULL,
    segundo_apellido VARCHAR2(30),
    fecha_nacimiento DATE NOT NULL,
    telefono VARCHAR2(15) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_MIEMBRO_REP FOREIGN KEY (idRepresentante) REFERENCES REPRESENTANTE(idRepresentante),
    CONSTRAINT FK_MIEMBRO_PAIS FOREIGN KEY (idPais_nacio) REFERENCES PAIS(idPais),
    CONSTRAINT FK_MIEMBRO_GRUPO FOREIGN KEY (idGrupo) REFERENCES GRUPO_LECTURA(idGrupo)
);

-- 12. HISTORICO MEMBRESIA
CREATE TABLE HISTORICO_MEMBRESIA (
    fecha_inicio DATE NOT NULL,
    idMiembro NUMBER(6) NOT NULL,
    idClub NUMBER(4) NOT NULL,
    fecha_fin DATE,
    estatus VARCHAR2(10) NOT NULL,
    motivo_deuda VARCHAR2(15),
    CONSTRAINT PK_HISTORICO PRIMARY KEY (fecha_inicio, idMiembro, idClub),
    CONSTRAINT FK_HM_MIEMBRO FOREIGN KEY (idMiembro) REFERENCES MIEMBRO(idMiembro),
    CONSTRAINT FK_HM_CLUB FOREIGN KEY (idClub) REFERENCES CLUB_LECTURA(idClub),
    CONSTRAINT CHECK_ESTATUS CHECK (estatus IN ('activo', 'inactivo')),
    CONSTRAINT CHECK_MOTIVO CHECK (motivo_deuda IN ('voluntario', 'deudas', 'Inasistencia', 'otro'))
);

-- 13. PAGO
CREATE TABLE PAGO (
    idPago NUMBER(6) PRIMARY KEY NOT NULL,
    fecha_inicio DATE NOT NULL,
    idMiembro NUMBER(6) NOT NULL,
    idClub NUMBER(4) NOT NULL,
    fecha_pago DATE NOT NULL,
    CONSTRAINT FK_PAGO_HM FOREIGN KEY (fecha_inicio, idMiembro, idClub) REFERENCES HISTORICO_MEMBRESIA(fecha_inicio, idMiembro, idClub)
);

-- 14. INASISTENCIA
CREATE TABLE INASISTENCIA (
    idMiembro NUMBER(6) NOT NULL,
    fecha DATE NOT NULL,
    idGrupo NUMBER(4) NOT NULL,
    estatus VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_INASISTENCIA PRIMARY KEY (idMiembro, fecha, idGrupo),
    CONSTRAINT FK_INAS_MIEMBRO FOREIGN KEY (idMiembro) REFERENCES MIEMBRO(idMiembro),
    CONSTRAINT FK_INAS_CALENDARIO FOREIGN KEY (fecha, idGrupo) REFERENCES CALENDARIO_MES_REUNION(fecha, idGrupo)
);

-- 15. AUTOR
CREATE TABLE AUTOR (
    idAutor NUMBER(6) PRIMARY KEY NOT NULL,
    primer_nombre VARCHAR2(30) NOT NULL,
    segundo_nombre VARCHAR2(30),
    primer_apellido VARCHAR2(30) NOT NULL,
    segundo_apellido VARCHAR2(30),
    nombre_ant_seudonimo VARCHAR2(50)
);

-- 16. LIBRO
CREATE TABLE LIBRO (
    ISBN VARCHAR2(20) PRIMARY KEY NOT NULL,
    titulo_original VARCHAR2(100) NOT NULL,
    año_publicacion NUMBER(4) NOT NULL,
    sinopsis VARCHAR2(500) NOT NULL,
    cantidad_paginas NUMBER(4) NOT NULL,
    tipo_narrativa VARCHAR2(20) NOT NULL,
    resumen_tema VARCHAR2(500) NOT NULL,
    CONSTRAINT CHECK_NARRATIVA CHECK (tipo_narrativa IN ('novela', 'cuento', 'leyenda', 'fabula', 'epopeya', 'mito'))
);

-- 17. AUTOR_LIBRO (Relación M:N entre Autor y Libro)
CREATE TABLE AUTOR_LIBRO (
    ISBN VARCHAR2(20) NOT NULL,
    idAutor NUMBER(6) NOT NULL,
    CONSTRAINT PK_AUTOR_LIBRO PRIMARY KEY (ISBN, idAutor),
    CONSTRAINT FK_AL_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
    CONSTRAINT FK_AL_AUTOR FOREIGN KEY (idAutor) REFERENCES AUTOR(idAutor)
);

-- 18. PREFERENCIA (Relación entre Miembro y Libro)
CREATE TABLE PREFERENCIA (
    idMiembro NUMBER(6) NOT NULL,
    ISBN VARCHAR2(20) NOT NULL,
    orden_preferencia NUMBER(1) NOT NULL,
    CONSTRAINT PK_PREFERENCIA PRIMARY KEY (idMiembro, ISBN),
    CONSTRAINT FK_PREF_MIEMBRO FOREIGN KEY (idMiembro) REFERENCES MIEMBRO(idMiembro),
    CONSTRAINT FK_PREF_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);

-- 19. G_LC (Grupo Lectura de Libros)
CREATE TABLE G_LC (
    fecha_inicio DATE NOT NULL,
    idGrupo NUMBER(4) NOT NULL,
    ISBN VARCHAR2(20) NOT NULL,
    fecha_fin DATE,
    CONSTRAINT PK_G_LC PRIMARY KEY (fecha_inicio, idGrupo, ISBN),
    CONSTRAINT FK_GLC_GRUPO FOREIGN KEY (idGrupo) REFERENCES GRUPO_LECTURA(idGrupo),
    CONSTRAINT FK_GLC_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);

-- 20. OBRA ACTUADA
CREATE TABLE OBRA_ACTUADA (
    idObra NUMBER(6) PRIMARY KEY NOT NULL,
    ISBN VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500) NOT NULL,
    costo_entrada NUMBER(10,2) NOT NULL,
    activo VARCHAR2(2) NOT NULL,
    CONSTRAINT FK_OBRA_LIBRO FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN),
    CONSTRAINT CHECK_ACTIVO CHECK (activo IN ('si', 'no'))
);

-- 21. ELENCO
CREATE TABLE ELENCO (
    idMiembro NUMBER(6) NOT NULL,
    idObra NUMBER(6) NOT NULL,
    CONSTRAINT PK_ELENCO PRIMARY KEY (idMiembro, idObra),
    CONSTRAINT FK_ELENCO_MIEMBRO FOREIGN KEY (idMiembro) REFERENCES MIEMBRO(idMiembro),
    CONSTRAINT FK_ELENCO_OBRA FOREIGN KEY (idObra) REFERENCES OBRA_ACTUADA(idObra)
);

-- 22. PRESENTACION
CREATE TABLE PRESENTACION (
    fecha_presentacion DATE NOT NULL,
    idObra NUMBER(6) NOT NULL,
    cantidad_asistentes NUMBER(5) NOT NULL,
    valoracion_obra VARCHAR2(1) NOT NULL,
    CONSTRAINT PK_PRESENTACION PRIMARY KEY (fecha_presentacion, idObra),
    CONSTRAINT FK_PRES_OBRA FOREIGN KEY (idObra) REFERENCES OBRA_ACTUADA(idObra),
    CONSTRAINT CHECK_VALORACION_OBRA CHECK (valoracion_obra IN ('1', '2', '3', '4', '5'))
);

-- 23. MEJOR ACTOR
CREATE TABLE MEJOR_ACTOR (
    idMiembro NUMBER(6) NOT NULL,
    idObra NUMBER(6) NOT NULL,
    fecha_presentacion DATE NOT NULL,
    CONSTRAINT PK_MEJOR_ACTOR PRIMARY KEY (idMiembro, idObra, fecha_presentacion),
    CONSTRAINT FK_MA_ELENCO FOREIGN KEY (idMiembro, idObra) REFERENCES ELENCO(idMiembro, idObra),
    CONSTRAINT FK_MA_PRESENTACION FOREIGN KEY (fecha_presentacion, idObra) REFERENCES PRESENTACION(fecha_presentacion, idObra)
);